service: AWS-Test-Website

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
      - http:
          path: /
          method: post

plugins:
  - serverless-offline
